### ISSUE TITLE
Generate HTML File

### ISSUE THREAD

**Issue by carlosricov** [MLH-Fellowship/LATAM-C-Turtles-Portfolio#5]
The starting code that will act as the base for our other features.

**Comment by Sukhamjot-Singh** [comment]
I am eager to help
What kind of HTML file is needed?

**Comment by carlosricov** [comment]
Just a base html file generated through Flask with Python

**Comment by carlosricov** [comment]
It's okay though! I'll take on this issue 👍🏻
